from enum import Enum, auto

class OpType(Enum):
    PUSH_INT = auto()
    PUSH_MEMORY = auto()
    PUSH_LOCAL_MEM = auto()
    PUSH_VAR = auto()
    PUSH_LOCAL_VAR = auto()
    PUSH_STR = auto()
    PUSH_NULL_STR = auto()
    PUSH_PROC = auto()
    CAST = auto()
    IF = auto()
    ELSE = auto()
    ENDIF = auto()
    WHILE = auto()
    ENDWHILE = auto()
    DEFPROC = auto()
    ENDPROC = auto()
    BIND = auto()
    PUSH_BIND_STACK = auto()
    UNBIND = auto()
    CALL = auto()
    TYPED_LOAD = auto()
    TYPED_STORE = auto()
    PACK = auto()
    UNPACK = auto()
    PUSH_FIELD = auto()
    PUSH_FIELD_PTR = auto()
    MOVE_STRUCT = auto()
    UPCAST = auto()
    CALL_LIKE = auto()
    INDEX = auto()
    INDEX_PTR = auto()
    AUTO_INIT = auto()
    SIZEOF = auto()
    SYSCALL = auto()
    OPERATOR = auto()

class Operator(Enum):
    ADD = auto()
    SUB = auto()
    MUL = auto()
    DIV = auto()
    DUP = auto()
    DROP = auto()
    SWAP = auto()
    ROT = auto()
    LT = auto()
    GT = auto()
    EQ = auto()
    LE = auto()
    GE = auto()
    NE = auto()
    STORE = auto()
    STRONG_STORE = auto()
    STORE8 = auto()
    LOAD = auto()
    LOAD8 = auto() 

class Op:
    def __init__(self, type: OpType, operand=None, loc: str = "") -> None:
        self.type: OpType = type
        self.operand = operand 
        self.loc: str = loc